### ISSUE TITLE
Update getRegionIntensity

### ISSUE THREAD

**Issue by tgibbons-css** [tgibbons-css/CEC_Prototype_2#2]
In the Architecture Tweeks branch, update RegionIntensityExtractor: getRegionIntensity() so it finds the average green pixel value in the region.  I think this code is there but commented out?

Figure out some way to also test this method on a region of a sample bitmap...

**Comment by milesliebren** [comment]
Fully implemented method. Gets every pixel using inRegion.getBitmapRegion(bitMap) and then calculates the overall intensity for that region based on all pixels.
